pipeline:
  test-syntax:
    image: xordspar0/love-build
    commands:
      - make check
      - make test

  package-love-dev:
    image: xordspar0/love-build
    when:
      event: push
      branch: master
    commands:
      - make love synthein_version=c${DRONE_COMMIT:8}

  package-love-release:
    image: xordspar0/love-build
    when:
      event: tag
      branch: refs/tags/*
    commands:
      - make love synthein_version=${DRONE_TAG}

  package-linux-appimage:
    image: xordspar0/love-build
    when:
      event: never
      branch: refs/tags/*
    commands:
      - make appimage synthein_version=${DRONE_TAG} love_version=0.10.2

  package-linux-snap:
    image: xordspar0/love-build
    when:
      event: tag
      branch: refs/tags/*
    commands:
      - apt-get update && apt-get -y install snapcraft
      - make snap synthein_version=${DRONE_TAG} love_version=0.10.2

  package-mac:
    image: xordspar0/love-build
    when:
      event: tag
      branch: refs/tags/*
    commands:
      - make mac synthein_version=${DRONE_TAG} love_version=0.10.2

  package-windows:
    image: xordspar0/love-build
    when:
      event: tag
      branch: refs/tags/*
    commands:
      - make windows synthein_version=${DRONE_TAG} love_version=0.10.2

  generate-dependency-graph:
    image: xordspar0/love-build
    secrets: [ BINTRAY_API_KEY ]
    when:
      event: push
      branch: master
    commands:
      - apt-get update && apt-get -y install graphviz
      - scripts/dependency-graph.lua src/main.lua --dot | dot -T png > out.png
      - "curl --fail -T out.png -uxordspar0:$${BINTRAY_API_KEY} 'https://api.bintray.com/content/xordspar0/Synthein/Meta/master/dependency-graph.png?publish=1&override=1'"

  telegram:
    image: appleboy/drone-telegram
    pull: true
    secrets: [ TELEGRAM_TOKEN ]
    when:
      event: push
      branch: master
      status: [failure, success, error]
    to: -1001143861626
    format: html
    message: >
      <b>Build {{ build.status }}</b>

      <a href="{{ build.link }}">{{ repo.owner }}/{{ repo.name }}</a> in branch
      <b>{{ commit.branch }}</b> by <b>{{ commit.author }}</b>.

      {{ commit.message }}
