pipeline:
  test-syntax:
    when:
      event: push
    image: synthein/love-build
    commands:
      - make check
      - make test

  package-dev:
    when:
      event: push
      branch: master
    image: synthein/love-build
    commands:
      - make love synthein_version=${DRONE_COMMIT:8}

  package-release:
    when:
      event: tag
      branch: refs/tags/*
    image: synthein/love-build
    commands:
      - make ${PACKAGE_FORMAT} synthein_version=${DRONE_TAG} love_version=0.10.2

  package-linux-snap:
    when:
      event: tag
      branch: refs/tags/*
    image: synthein/love-build
    commands:
      - apt-get update && apt-get -y install snapcraft
      - make snap synthein_version=${DRONE_TAG} love_version=0.10.2

  generate-dependency-graph:
    when:
      event: push
      branch: master
    image: synthein/love-build
    secrets: [ BINTRAY_API_KEY ]
    commands:
      - apt-get update && apt-get -y install graphviz
      - scripts/dependency-graph.lua src/main.lua --dot | dot -T png > out.png
      # Disabled because bintray won't allow us to update this file anymore.
      #- "curl --fail -T out.png -uxordspar0:$${BINTRAY_API_KEY} 'https://api.bintray.com/content/xordspar0/Synthein/Meta/master/dependency-graph.png?publish=1&override=1'"

  telegram:
    when:
      event: push
      branch: master
      status: [failure, success, error]
    image: appleboy/drone-telegram
    pull: true
    secrets: [ TELEGRAM_TOKEN ]
    to: -1001143861626
    format: html
    message: >
      <a href="{{ build.link }}">Build {{ build.status }}</a>

      <a href="https://github.com/synthein/synthein">{{ repo.owner }}/{{ repo.name }}</a> in branch
      <b>{{ commit.branch }}</b> by <b>{{ commit.author }}</b>.

      {{ commit.message }}

matrix:
  PACKAGE_FORMAT:
    - love
    #- appimage # Doesn't work yet.
    - mac
    - windows
