pipeline:
  test-syntax:
    image: abaez/lua:latest
    commands:
      - apk update && apk add make
      - make check
      - make test

  package-love-dev:
    image: alpine:latest
    when:
      event: push
      branch: master
    commands:
      - export SYNTHEIN_VERSION=c${DRONE_COMMIT:8}
      - apk update && apk add zip
      - scripts/package-love.sh

  package-love-release:
    image: alpine:latest
    when:
      event: tag
      branch: refs/tags/*
    commands:
      - export SYNTHEIN_VERSION=${DRONE_TAG}
      - apk update && apk add zip
      - scripts/package-love.sh

  package-linux-appimage:
    image: ubuntu:14.04
    when:
      event: never
      branch: refs/tags/*
    commands:
      - export SYNTHEIN_VERSION=${DRONE_TAG}
      - export LOVE_VERSION=0.10.2
      - apt-get update && apt-get -y install curl zip
      - scripts/package-linux-appimage.sh

  package-linux-snap:
    image: ubuntu:16.04
    when:
      event: tag
      branch: refs/tags/*
    commands:
      - export SYNTHEIN_VERSION=${DRONE_TAG}
      - export LOVE_VERSION=0.10.2
      - apt-get update && apt-get -y install binutils curl xz-utils
      - scripts/package-linux-snap.sh

  package-mac:
    image: alpine:latest
    when:
      event: tag
      branch: refs/tags/*
    commands:
      - export SYNTHEIN_VERSION=${DRONE_TAG}
      - export LOVE_VERSION=0.10.2
      - apk update && apk add curl zip
      - scripts/package-mac.sh

  package-windows:
    image: alpine:latest
    when:
      event: tag
      branch: refs/tags/*
    commands:
      - export SYNTHEIN_VERSION=${DRONE_TAG}
      - export LOVE_VERSION=0.10.2
      - apk update && apk add curl zip
      - scripts/package-windows.sh

  generate-dependency-graph:
    image: abaez/lua:latest
    secrets: [ BINTRAY_API_KEY ]
    when:
      event: push
      branch: master
    commands:
      - apk update && apk add graphviz
      - scripts/dependency-graph.lua src/main.lua --dot | dot -T png > out.png
      - 'curl --fail -T out.png -uxordspar0:$${BINTRAY_API_KEY} https://api.bintray.com/content/xordspar0/Synthein/Meta/master/dependency-graph.png?publish=1&override=1'

  telegram:
    image: appleboy/drone-telegram
    pull: true
    secrets: [ TELEGRAM_TOKEN ]
    when:
      event: push
      branch: master
      status: [failure, success, error]
    to: -1001143861626
    format: html
    message: >
      <b>Build {{ build.status }}</b>

      <a href="{{ build.link }}">{{ repo.owner }}/{{ repo.name }}</a> in branch
      <b>{{ commit.branch }}</b> by <b>{{ commit.author }}</b>.

      {{ commit.message }}
