package-config-release: &package-config-release
  when:
    event: tag
  image: synthein/love-build
  environment:
    - LOVE_VERSION=0.10.2

pipeline:
  test-syntax:
    when:
      event: push
    image: synthein/love-build
    pull: true
    commands:
      - make check
      - make test

  package-love-dev:
    when:
      event: push
      branch: master
    image: synthein/love-build
    commands:
      - make love synthein_version=${DRONE_COMMIT:8}

  package-love-release:
    <<: *package-config-release
    commands:
      - make love synthein_version=${DRONE_TAG}

  package-linux-appimage:
    <<: *package-config-release
    commands:
      - make appimage synthein_version=${DRONE_TAG} love_version=$${LOVE_VERSION}

  # package-linux-snap:
  #   <<: *package-config-release
  #   commands:
  #     - make snap synthein_version=${DRONE_TAG} love_version=$${LOVE_VERSION}

  package-mac:
    <<: *package-config-release
    commands:
      - make mac synthein_version=${DRONE_TAG} love_version=$${LOVE_VERSION}

  package-windows:
    <<: *package-config-release
    commands:
      - make windows synthein_version=${DRONE_TAG} love_version=$${LOVE_VERSION}

  upload-builds:
    when:
      event: tag
    image: plugins/github-release
    secrets: [ github_token ]
    files: build/synthein-${DRONE_TAG}*

  telegram:
    when:
      event: push
      branch: master
      status: [failure, success, error]
    image: appleboy/drone-telegram
    pull: true
    secrets: [ telegram_token ]
    to: -1001143861626
    format: html
    message: >
      <a href="{{ build.link }}">Build {{ build.status }}</a>

      <a href="https://github.com/synthein/synthein">{{ repo.owner }}/{{ repo.name }}</a> in branch
      <b>{{ commit.branch }}</b> by <b>{{ commit.author }}</b>.

      {{ commit.message }}
