release-package-config: &release-package-config
  when:
    event: tag
    branch: refs/tags/*
  image: synthein/love-build
  environment:
    - LOVE_VERSION=0.10.2

pipeline:
  test-syntax:
    when:
      event: push
    image: synthein/love-build
    pull: true
    commands:
      - make check
      - make test

  generate-dependency-graph:
    when:
      event: push
      branch: master
    image: synthein/love-build
    secrets: [ BINTRAY_API_KEY ]
    commands:
      - scripts/dependency-graph.lua src/main.lua --dot | dot -T png > out.png

  package-love-dev:
    when:
      event: push
      branch: master
    image: synthein/love-build
    commands:
      - make love synthein_version=${DRONE_COMMIT:8}

  package-love-release:
    <<: *release-package-config
    commands:
      - make love synthein_version=${DRONE_TAG}

  package-linux-appimage:
    <<: *release-package-config
    commands:
      - make appimage synthein_version=${DRONE_TAG} love_version=$${LOVE_VERSION}

  package-linux-snap:
    <<: *release-package-config
    commands:
      - make snap synthein_version=${DRONE_TAG} love_version=$${LOVE_VERSION}

  package-mac:
    <<: *release-package-config
    commands:
      - make mac synthein_version=${DRONE_TAG} love_version=$${LOVE_VERSION}

  package-windows:
    <<: *release-package-config
    commands:
      - make windows synthein_version=${DRONE_TAG} love_version=$${LOVE_VERSION}

  telegram:
    when:
      event: push
      branch: master
      status: [failure, success, error]
    image: appleboy/drone-telegram
    pull: true
    secrets: [ TELEGRAM_TOKEN ]
    to: -1001143861626
    format: html
    message: >
      <a href="{{ build.link }}">Build {{ build.status }}</a>

      <a href="https://github.com/synthein/synthein">{{ repo.owner }}/{{ repo.name }}</a> in branch
      <b>{{ commit.branch }}</b> by <b>{{ commit.author }}</b>.

      {{ commit.message }}
