pipeline:
    test-syntax:
        image: alpine:latest
        commands:
            - apk update && apk add lua curl zip
            - find src -name '*.lua' -exec luac -p {} +

    package-love:
        image: alpine:latest
        when:
            event: [push, tag]
            branch: [master, refs/tags/*]
        commands:
            - scripts/package-love.sh

    package-windows:
        image: alpine:latest
        when:
            event: tag
            branch: refs/tags/*
        commands:
            - export LOVE_VERSION=0.10.2
            - scripts/package-windows.sh
